name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Or whichever branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (if needed for building)
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Specify your Node version if using Node.js

      - name: Install dependencies
        run: npm install # Run this if using npm to install dependencies

      - name: Build project
        run: npm run build # Or use your project's build command

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # Branch to deploy to
          folder: build # Folder where the build output is stored
